### PR TITLE
16 lint and prettier check on prs

### PR DESCRIPTION
**Pull request by okunamayanad**

### CODE REVIEW

**Comment by okunamayanad** [comment]
Waiting for @tkbstudios to adjust project actions settings

**Review by tkbstudios — APPROVED** [review]
noice seems fine and doesn't have any issues, just why Prettier thinking there are issues with "use client"; ?
This is what I mean:
image

**Review by tkbstudios — APPROVED** [review]
noice

**Comment by okunamayanad** [comment]
> noice seems fine and doesn't have any issues, just why Prettier thinking there are issues with "use client"; ? This is what I mean: image

Weird, it didnt show the correct line, maybe because there were multiple lines of broken code? I'm not entirely sure

The file and the error was correct though, [prettified here](https://github.com/tkbstudios/CC-Bank-frontend/pull/23/commits/6d1ecd41b83c2f6dd4d8cb2a7608c20542c719a4)

**Review by tkbstudios — APPROVED** [review]

**Review by tkbstudios — APPROVED** [review]
yay

**Pull request merged**
