### PR TITLE
Sub navigation bar for dashboard pages

### PR DESCRIPTION
**Pull request by Exzotic5485**
Adds a navbar under the dashboard layout to navigate between the dashboard pages.
image

### CODE REVIEW

**Comment by okunamayanad** [comment]
Wouldn't it be better to just use the current navbar instead of creating another one?

**Comment by Exzotic5485** [comment]
It would work in the current navbar fine but I felt like the dashboard pages should be separate to the rest of the site in case you wanted to add any other public / non authed pages, so the dashboard is sort of in its own section.

**Comment by okunamayanad** [comment]
> It would work in the current navbar fine but I felt like the dashboard pages should be separate to the rest of the site in case you wanted to add any other public / non authed pages, so the dashboard is sort of in its own section.

Great thinking but we currently use the dashboard as a place to put private / authed items. As you said we'll probably need a place to put non authed public pages too. Maybe we should make navbar a place to put public pages, seperate it with a vertical seperator, put only one button for logins and move all private authed items into this subnav. What do you think? also @tkbstudios

Like this:
321981406-f85f1a9a-c5f8-49c3-94a2-f5a40e540861

**Comment by tkbstudios** [comment]
I kinda like it how it is now ngl, have dashboard pages separated from the other navbar

**Comment by tkbstudios** [comment]
@okunamayanad can I merge?

**Comment by tkbstudios** [comment]
Sorry that it took a bit long lol but there u go, the merge :p

**Pull request merged**
